print(bool(""))
print(bool(0))
print(bool(False))
print(bool(-1))
print(bool("False"))
print(bool(5))
print(bool(10 >= 3))
print(bool(10 == 10))
print(bool(10 == "10"))
print(bool(10 != "10"))
print(bool("bag" > "apple"))
print(bool("bag" > "Bag"))
print(ord("b"))
print(ord("B"))
